import { Brain, ArrowRight } from 'lucide-react';

export function AIInsightsPanel() {
  const insights = [
    { title: "EC2 Demand Spike", explanation: "Costs increased by 18% due to anomalous scaling of the e-commerce backend cluster in us-east-1 during off-peak hours.", recommendation: "Implement stricter scaling bounds for 'backend-production' Auto Scaling Group.", impact: "-$450/wk", isApplied: false },
    { title: "Storage Optimization", explanation: "Detected 4 unattached EBS volumes left over from terminated c5.xlarge instances in the development environment.", recommendation: "Automatically snapshot and delete unattached volumes older than 7 days.", impact: "-$124/wk", isApplied: true }
  ];

  return (
    <div className="max-w-[900px] mx-auto pt-6 pb-24 antialiased text-white/90 flex flex-col items-center">
      
      {/* HEADER */}
      <div className="mb-16 text-center">
        <div className="w-12 h-12 bg-indigo-500/10 border border-indigo-500/20 rounded-2xl flex items-center justify-center mx-auto mb-4">
           <Brain className="w-6 h-6 text-indigo-400" />
        </div>
        <h1 className="text-3xl font-semibold tracking-tight text-white mb-3">Diagnostic Insights</h1>
        <p className="text-sm text-zinc-400 max-w-md">Plain-english explanations for complex cloud billing anomalies, generated by Sentinel AI.</p>
      </div>

      {/* Insights Stream */}
      <div className="w-full space-y-6">
        {insights.map((insight, idx) => (
          <div key={idx} className="bg-[#111113]/50 border border-white/5 rounded-3xl p-8 hover:bg-white/[0.02] transition-colors relative group">
            <h2 className="text-xl font-semibold text-white mb-2">{insight.title}</h2>
            <p className="text-base text-zinc-300 leading-relaxed max-w-2xl font-light mb-8">
              {insight.explanation}
            </p>

            <div className="flex flex-col md:flex-row gap-4 items-start md:items-center justify-between p-4 bg-black/20 rounded-2xl border border-white/5">
               <div>
                  <p className="text-xs text-zinc-500 font-medium mb-1 uppercase tracking-wider">Suggested Action</p>
                  <p className="text-sm text-zinc-200 font-medium">{insight.recommendation}</p>
               </div>
               
               <div className="flex items-center gap-4 shrink-0">
                  <span className="text-sm font-bold text-emerald-400">{insight.impact}</span>
                  {insight.isApplied ? (
                    <span className="px-4 py-2 bg-white/5 text-zinc-500 rounded-xl text-xs font-bold uppercase cursor-not-allowed">
                       Applied
                    </span>
                  ) : (
                    <button className="px-4 py-2 bg-indigo-600 hover:bg-indigo-500 text-white rounded-xl text-xs font-bold uppercase transition-colors shadow-lg shadow-indigo-500/20 flex items-center gap-2 group-hover:pr-3">
                       Execute
                       <ArrowRight className="w-3 h-3 opacity-0 -ml-2 group-hover:opacity-100 group-hover:ml-0 transition-all" />
                    </button>
                  )}
               </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
